"""
Annotate entities extracted from a React Native repo with one-line
descriptions generated by an LLM (local via LM Studio, or remote via Groq).

This version is RESUMABLE: results are written to the output file as soon
as each one completes (not buffered until the end), and on rerun it reads
the existing output file first and skips any files that already have a
successful result. This means if you hit a rate limit, get disconnected,
or kill the script partway through, you can just run it again and it will
pick up where it left off.

Usage:
    python add_descriptions_stepped.py --llm local
    python add_descriptions_stepped.py --llm remote            # uses env var according to config
    python add_descriptions_stepped.py --llm remote --retry-errors  # also retry previously-failed files

Input:
    ../data/processed/entities.jsonl
        JSON-lines file where each record has at least a "type" field.
        Records with type == "File" must have a "file" field (relative to
        --root-folder) pointing at a source file. Other records reference
        that file via either a "file" or "file" field.

Output (written incrementally, one line per file, as each completes):
    ../data/processed/entities_raw_results.jsonl
        Intermediate/checkpoint file: one record per source file, either
        {"file": ..., "entities": [...]} or {"file": ..., "error": ...}.
        This is what makes the run resumable - re-running the script reads
        this file first.

    ../data/processed/entities_with_desc.jsonl
        Final merged output. Same records as the input, but entities that
        were successfully annotated now also have a "description" field.
        Written once at the end, after all files are processed (or after
        every checkpoint if --write-final-every-checkpoint is set).
"""

import argparse
import json
import os
import re
import threading
import time
from itertools import islice
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

PROMPT_TEMPLATE = """
You will receive the content from a typescript file in a React Native App. You will also receive a summary of entities on the page as a set of json objects.
Your task is to create a new key called "description" for each of the entities with a ONE LINE description of the entity - what it is intended for.

Respond with ONLY the updated JSON array. No explanation, no markdown code fences.

FILE CONTENT START
{file_content}
FILE CONTENT END

ENTITIES:
{entities}
"""

SYSTEM_PROMPT = "You are a precise code documentation assistant. Output valid JSON only."

from dotenv import load_dotenv
load_dotenv()

DEFAULT_CONFIG_PATH = Path(os.getenv("LLM_CONFIG_PATH", "src/ts_extract/llm_config.json"))

# --------------------------------------------------------------------------
# Config loading
# --------------------------------------------------------------------------

def load_llm_config(config_path: Path = DEFAULT_CONFIG_PATH) -> dict:
    if not config_path.exists():
        raise FileNotFoundError(f"LLM config file not found: {config_path}")
    with open(config_path, "r") as f:
        return json.load(f)
    
# --------------------------------------------------------------------------
# LLM construction
# --------------------------------------------------------------------------

def build_llm(
    backend: str,
    max_tokens: int,
    config = load_llm_config(DEFAULT_CONFIG_PATH)
) -> ChatOpenAI:
    """Build a ChatOpenAI client pointed at whichever backend is selected,
    using settings from llm_config.json."""

    if backend not in config:
        available = ", ".join(sorted(config.keys()))
        raise ValueError(f"Unknown backend: {backend!r} (available: {available})")

    entry = config[backend]

    # Resolve API key: explicit override > env var from config > literal key in config
    api_key = (
        (os.environ.get(entry["api_key_env"]) if entry.get("api_key_env") else None)
        or entry.get("api_key")
    )

    if entry.get("requires_key", True) and not api_key:
        raise ValueError(
            f"Backend {backend!r} requires an API key but none was found. "
            f"Set {entry.get('api_key_env') or 'api_key'} in the environment "
            f"or in {DEFAULT_CONFIG_PATH}."
        )

    # Local backends often don't validate the key at all, so fall back to a placeholder
    if not api_key:
        api_key = "not-needed"

    return ChatOpenAI(
        base_url=entry["base_url"],
        api_key=api_key,
        model=entry["model"],
        max_tokens=max_tokens,
    )


# --------------------------------------------------------------------------
# Data loading
# --------------------------------------------------------------------------

def read_jsonl_file(jsonl_path: str) -> list[dict]:
    """Read a JSON Lines file, returning a list of dicts (one per line)."""
    records = []
    if not os.path.exists(jsonl_path):
        return records
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def build_file_entity_map(data: list[dict], root_folder: str) -> dict[Path, list[dict]]:
    """Group entities by the source file they belong to.

    Entities of type "File" define the files to process. Any other entity
    that references that same path (via a "file" or "file" key) is grouped
    under it.
    """
    files = [entity["file"] for entity in data if entity.get("type") == "File"]

    file_entity_map: dict[Path, list[dict]] = {}
    for file_path in files:
        entities = [
            entity for entity in data
            if entity.get("file") == file_path
        ]
        file_entity_map[Path(root_folder) / file_path] = entities

    return file_entity_map


# --------------------------------------------------------------------------
# Checkpoint (resumable results) handling
# --------------------------------------------------------------------------

class Checkpoint:
    """Tracks per-file results and streams them to disk as they arrive.

    Thread-safe: process_file() runs on worker threads, all of which call
    record() when they finish.
    """

    def __init__(self, checkpoint_path: str, retry_errors: bool):
        self.checkpoint_path = checkpoint_path
        self._lock = threading.Lock()
        self.done: dict[str, dict] = {}  # file -> result record

        for record in read_jsonl_file(checkpoint_path):
            file_key = record.get("file")
            if file_key is None:
                continue
            if "error" in record and retry_errors:
                continue  # don't count previous errors as done; will be retried
            self.done[file_key] = record

        # Open in append mode - existing good lines stay, new ones get added.
        # (We never rewrite the checkpoint file in place, only append.)
        self._fh = open(checkpoint_path, "a", encoding="utf-8")

    def is_done(self, file_key: str) -> bool:
        return file_key in self.done

    def record(self, result: dict):
        file_key = result["file"]
        with self._lock:
            self.done[file_key] = result
            self._fh.write(json.dumps(result) + "\n")
            self._fh.flush()
            os.fsync(self._fh.fileno())

    def all_results(self) -> list[dict]:
        with self._lock:
            return list(self.done.values())

    def close(self):
        self._fh.close()


# --------------------------------------------------------------------------
# LLM querying
# --------------------------------------------------------------------------

def build_prompt(file_content: str, entities: list[dict]) -> str:
    return PROMPT_TEMPLATE.format(
        file_content=file_content,
        entities=json.dumps(entities, indent=2),
    )


def extract_json(text: str):
    """Strip markdown fences / stray text if the model doesn't fully obey
    the 'JSON only' instruction."""
    text = text.strip()
    match = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
    if match:
        text = match.group(1).strip()
    return json.loads(text)


def is_rate_limit_error(exc: Exception) -> bool:
    msg = str(exc).lower()
    return "429" in msg or "rate_limit" in msg or "rate limit" in msg


def process_file(llm: ChatOpenAI, ts_path: Path, entities: list[dict],
                  max_retries: int, base_backoff: float) -> dict:
    try:
        file_content = ts_path.read_text(encoding="utf-8")
    except OSError as e:
        return {"file": str(ts_path), "error": f"Could not read file: {e}"}

    prompt = build_prompt(file_content, entities)
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    last_error = None
    for attempt in range(max_retries + 1):
        try:
            response = llm.invoke(messages)
        except Exception as e:
            last_error = e
            if is_rate_limit_error(e) and attempt < max_retries:
                wait = base_backoff * (2 ** attempt)
                print(f"[RATE LIMIT] {ts_path} - waiting {wait:.0f}s (attempt {attempt + 1}/{max_retries})")
                time.sleep(wait)
                continue
            return {"file": str(ts_path), "error": f"LLM call failed: {e}"}

        try:
            result = extract_json(response.content)
        except json.JSONDecodeError as e:
            return {"file": str(ts_path), "error": f"JSON parse failed: {e}", "raw": response.content}

        return {"file": str(ts_path), "entities": result}

    return {"file": str(ts_path), "error": f"LLM call failed after retries: {last_error}"}


class Pacer:
    """Very simple global pacer so concurrent workers don't collectively
    blow through RPM/TPM limits. Ensures at least `min_interval` seconds
    pass between the *start* of any two requests, across all threads."""

    def __init__(self, min_interval: float):
        self.min_interval = min_interval
        self._lock = threading.Lock()
        self._last_call = 0.0

    def wait_turn(self):
        with self._lock:
            now = time.monotonic()
            wait = self._last_call + self.min_interval - now
            if wait > 0:
                time.sleep(wait)
            self._last_call = time.monotonic()


def process_repo(llm: ChatOpenAI, file_entity_map: dict[Path, list[dict]],
                  checkpoint: Checkpoint, max_workers: int,
                  min_interval: float, max_retries: int, base_backoff: float):
    pacer = Pacer(min_interval)

    to_process = {
        path: entities for path, entities in file_entity_map.items()
        if not checkpoint.is_done(str(path))
    }
    skipped_count = len(file_entity_map) - len(to_process)
    if skipped_count:
        print(f"[INFO] Skipping {skipped_count} file(s) already in checkpoint")
    print(f"[INFO] Processing {len(to_process)} file(s)")

    if not to_process:
        return

    from concurrent.futures import ThreadPoolExecutor, as_completed

    def worker(path, entities):
        pacer.wait_turn()
        result = process_file(llm, path, entities, max_retries, base_backoff)
        checkpoint.record(result)
        return result

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(worker, path, entities): path
            for path, entities in to_process.items()
        }
        completed = 0
        for future in as_completed(futures):
            path = futures[future]
            completed += 1
            try:
                result = future.result()
                if "error" in result:
                    print(f"[FAILED {completed}/{len(to_process)}] {path}: {result['error']}")
                else:
                    print(f"[OK {completed}/{len(to_process)}] {path} ({len(result['entities'])} entities)")
            except Exception as e:
                print(f"[FAILED {completed}/{len(to_process)}] {path}: {e}")
                checkpoint.record({"file": str(path), "error": str(e)})


# --------------------------------------------------------------------------
# Merge descriptions back into the full dataset
# --------------------------------------------------------------------------

def merge_descriptions(data: list[dict], results: list[dict]) -> list[dict]:
    desc_lookup: dict[tuple, str] = {}
    for r in results:
        if "error" in r:
            continue
        entities = r.get("entities", [])
        if not isinstance(entities, list):
            print(f"[WARN] {r.get('file')}: 'entities' is not a list ({type(entities).__name__}), skipping")
            continue
        for ent in entities:
            if not isinstance(ent, dict):
                print(f"[WARN] {r.get('file')}: entity is not a dict ({type(ent).__name__}: {ent!r}), skipping")
                continue
            key_name = ent.get("id") or ent.get("file") or ent.get("name") or json.dumps(ent, sort_keys=True)
            if not isinstance(key_name, (str, int, float, bool)):
                key_name = json.dumps(key_name, sort_keys=True)
            desc_lookup[(r["file"], key_name)] = ent.get("description")

    updated = []
    for entity in data:
        entity = dict(entity)
        key_name = entity.get("id") or entity.get("file") or entity.get("name")
        if not isinstance(key_name, (str, int, float, bool)):
            key_name = json.dumps(key_name, sort_keys=True)

        entity_file = entity.get("file")

        for (file_key, name_key), desc in desc_lookup.items():
            if not isinstance(file_key, str):
                continue
            if name_key != key_name:
                continue
            file_key_norm = file_key.replace("\\", "/")
            file_match = isinstance(entity_file, str) and file_key_norm.endswith(entity_file.replace("\\", "/"))
            if file_match:
                entity["description"] = desc
                break
        updated.append(entity)
    return updated


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    _llm_config = load_llm_config()
    parser.add_argument("--tag", required=True,
                        help="Folder tag, e.g. <owner>_<repo>_<branch>. "
                             "Reads from data/raw/<tag>/ and data/processed/<tag>/, "
                             "writes to data/processed/<tag>/")
    parser.add_argument("--llm", choices=sorted(_llm_config.keys()),
                        default=os.environ.get("LLM_BACKEND", "local"),
                        help=f"Which LLM backend to use (default: local, or $LLM_BACKEND if set). "
                             f"Available: {', '.join(sorted(_llm_config.keys()))}")
    parser.add_argument("--max-tokens", type=int, default=2048)
    parser.add_argument("--num-files", type=int, default=None, help="Only process the first N files (default: all)")
    parser.add_argument("--max-workers", type=int, default=2, help="Concurrent LLM requests")
    parser.add_argument("--min-interval", type=float, default=2.5,
                        help="Minimum seconds between the start of any two requests (global pacer, across all workers)")
    parser.add_argument("--max-retries", type=int, default=1, help="Retries on rate-limit (429) errors before giving up on a file")
    parser.add_argument("--base-backoff", type=float, default=5.0, help="Base seconds for exponential backoff on rate limits")
    parser.add_argument("--retry-errors", action="store_true",
                        help="Also retry files that previously failed (default: only skip successes, errors are retried automatically)")
    args = parser.parse_args()

    processed_dir = os.path.join("data", "processed", args.tag)
    root_folder = os.path.join("data", "raw", args.tag)
    input_path = os.path.join(processed_dir, "entities.jsonl")
    output_path = os.path.join(processed_dir, "entities_with_desc.jsonl")
    log_folderpath = os.path.join(processed_dir, "add-descriptions-intermediate")

    checkpoint_path = os.path.join(log_folderpath, "entities_raw_results.jsonl")

    if not os.path.isdir(root_folder):
        parser.error(f"Root folder not found: {root_folder}")
    if not os.path.isfile(input_path):
        parser.error(f"Input entities file not found: {input_path}")

    os.makedirs(processed_dir, exist_ok=True)
    os.makedirs(log_folderpath, exist_ok=True)

    llm = build_llm(
        backend=args.llm,
        max_tokens=args.max_tokens,
        config = _llm_config
    )
    print(f"[INFO] Using {args.llm} backend "
          f"({'qwen3.5-4b' if args.llm == 'local' else 'llama-3.1-8b-instant'})")

    data = read_jsonl_file(input_path)
    file_entity_map = build_file_entity_map(data, root_folder)

    if args.num_files is not None:
        file_entity_map = dict(islice(file_entity_map.items(), args.num_files))

    checkpoint = Checkpoint(checkpoint_path, retry_errors=args.retry_errors)

    try:
        process_repo(
            llm, file_entity_map, checkpoint,
            max_workers=args.max_workers,
            min_interval=args.min_interval,
            max_retries=args.max_retries,
            base_backoff=args.base_backoff,
        )
    finally:
        checkpoint.close()

    results = checkpoint.all_results()
    num_errors = sum(1 for r in results if "error" in r)
    print(f"[INFO] Checkpoint has {len(results)} total result(s), {num_errors} error(s)")

    merged = merge_descriptions(data, results)

    with open(output_path, "w", encoding="utf-8") as f:
        for entry in merged:
            f.write(json.dumps(entry) + "\n")

    print(f"[INFO] Wrote {len(merged)} entities to {output_path}")
    if num_errors:
        print(f"[INFO] {num_errors} file(s) still have errors - rerun the same command "
              f"(errors are retried automatically) to pick those up.")


if __name__ == "__main__":
    main()