"""
Annotate entities extracted from a React Native repo with one-line
descriptions generated by an LLM (local via LM Studio, or remote via Groq).

This version is RESUMABLE: results are written to the output file as soon
as each one completes (not buffered until the end), and on rerun it reads
the existing output file first and skips any files that already have a
successful result. This means if you hit a rate limit, get disconnected,
or kill the script partway through, you can just run it again and it will
pick up where it left off.

Usage:
    python add_descriptions_stepped.py --llm local --tag raysk4ever_Simple-React-Native-App_main

Input:
    ../data/processed/entities.jsonl
        JSON-lines file where each record has at least a "type" field.
        Records with type == "File" must have a "file" field (relative to
        --root-folder) pointing at a source file. Other records reference
        that file via either a "file" or "file" field.

Output (written incrementally, one line per file, as each completes):
    ../data/processed/entities_raw_results.jsonl
        Checkpoint file: one record per SUCCESSFULLY processed source file,
        of the form {"file": ..., "entities": [...]}. A file only lands
        here once its LLM response has been parsed as JSON *and* validated
        to contain exactly the same set of entity identifiers as the
        input (no omissions, no additions). Failures of any kind
        (LLM errors, JSON parse failures, entity mismatches) are never
        written here - they only go to the metrics log below, and the
        file is simply retried on the next run since it's absent from
        the checkpoint.

    ../data/processed/add-descriptions-intermediate/llm_call_metrics.jsonl
        Append-only log of every LLM call attempt: timestamp, file,
        backend/model, attempt number, latency, token usage (when the
        backend reports it), and status ("success" or "error" with a
        message). This is the place to look when something failed - the
        checkpoint file itself never contains error records anymore.

    ../data/processed/entities_with_desc.jsonl
        Final merged output. Same records as the input, but entities that
        were successfully annotated now also have a "description" field.
        Written once at the end, after all files are processed (or after
        every checkpoint if --write-final-every-checkpoint is set).
"""

import argparse
import json
import os
import re
import threading
import time
from itertools import islice
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

PROMPT_TEMPLATE = """
You will receive the content from a typescript file in a React Native App. You will also receive a summary of entities on the page as a set of json objects.
Your task is to create a new key called "description" for each of the entities with a ONE LINE description of the entity - what it is intended for.

Respond with ONLY the updated JSON array. No explanation, no markdown code fences.

FILE CONTENT START
{file_content}
FILE CONTENT END

ENTITIES:
{entities}
"""

SYSTEM_PROMPT = "You are a precise code documentation assistant. Output valid JSON only."

from dotenv import load_dotenv
load_dotenv()

DEFAULT_CONFIG_PATH = Path(os.getenv("LLM_CONFIG_PATH", "src/ts_extract/llm_config.json"))

# --------------------------------------------------------------------------
# Config loading
# --------------------------------------------------------------------------

def load_llm_config(config_path: Path = DEFAULT_CONFIG_PATH) -> dict:
    if not config_path.exists():
        raise FileNotFoundError(f"LLM config file not found: {config_path}")
    with open(config_path, "r") as f:
        return json.load(f)

# --------------------------------------------------------------------------
# LLM construction
# --------------------------------------------------------------------------

def build_llm(
    backend: str,
    max_tokens: int,
    config = load_llm_config(DEFAULT_CONFIG_PATH)
) -> ChatOpenAI:
    """Build a ChatOpenAI client pointed at whichever backend is selected,
    using settings from llm_config.json."""

    if backend not in config:
        available = ", ".join(sorted(config.keys()))
        raise ValueError(f"Unknown backend: {backend!r} (available: {available})")

    entry = config[backend]

    # Resolve API key: explicit override > env var from config > literal key in config
    api_key = (
        (os.environ.get(entry["api_key_env"]) if entry.get("api_key_env") else None)
        or entry.get("api_key")
    )

    if entry.get("requires_key", True) and not api_key:
        raise ValueError(
            f"Backend {backend!r} requires an API key but none was found. "
            f"Set {entry.get('api_key_env') or 'api_key'} in the environment "
            f"or in {DEFAULT_CONFIG_PATH}."
        )

    # Local backends often don't validate the key at all, so fall back to a placeholder
    if not api_key:
        api_key = "not-needed"

    return ChatOpenAI(
        base_url=entry["base_url"],
        api_key=api_key,
        model=entry["model"],
        max_tokens=max_tokens,
    )


# --------------------------------------------------------------------------
# Data loading
# --------------------------------------------------------------------------

def read_jsonl_file(jsonl_path: str) -> list[dict]:
    """Read a JSON Lines file, returning a list of dicts (one per line)."""
    records = []
    if not os.path.exists(jsonl_path):
        return records
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def build_file_entity_map(data: list[dict], root_folder: str) -> dict[Path, list[dict]]:
    """Group entities by the source file they belong to.

    Entities of type "File" define the files to process. Any other entity
    that references that same path (via a "file" or "file" key) is grouped
    under it.
    """
    files = [entity["file"] for entity in data if entity.get("type") == "File"]

    file_entity_map: dict[Path, list[dict]] = {}
    for file_path in files:
        entities = [
            entity for entity in data
            if entity.get("file") == file_path
        ]
        file_entity_map[Path(root_folder) / file_path] = entities

    return file_entity_map


# --------------------------------------------------------------------------
# Entity identity helpers (shared by validation + merge)
# --------------------------------------------------------------------------

def entity_key(ent: dict):
    """Stable identifier for an entity: prefer id, then file, then name,
    falling back to a full serialization so we always get *something*
    hashable and comparable."""
    key_name = ent.get("id") or ent.get("file") or ent.get("name") or json.dumps(ent, sort_keys=True)
    if not isinstance(key_name, (str, int, float, bool)):
        key_name = json.dumps(key_name, sort_keys=True)
    return key_name


def validate_entity_keys(input_entities: list[dict], returned_entities: list) -> tuple[bool, str]:
    """Check that the LLM didn't omit or invent any entities: the set of
    identifiers in the response must exactly match the set in the input."""
    input_keys = {entity_key(e) for e in input_entities}

    returned_keys = set()
    for ent in returned_entities:
        if not isinstance(ent, dict):
            return False, f"entity is not a dict: {ent!r}"
        returned_keys.add(entity_key(ent))

    missing = input_keys - returned_keys
    extra = returned_keys - input_keys
    if missing or extra:
        parts = []
        if missing:
            parts.append(f"missing={sorted(str(k) for k in missing)}")
        if extra:
            parts.append(f"extra={sorted(str(k) for k in extra)}")
        return False, "; ".join(parts)
    return True, ""


# --------------------------------------------------------------------------
# Metrics / call log
# --------------------------------------------------------------------------

class MetricsLog:
    """Append-only, thread-safe log of every LLM call attempt: latency,
    token usage, and success/error status. Separate from the checkpoint
    file, which only ever holds successful, validated results."""

    def __init__(self, log_path: str):
        self.log_path = log_path
        self._lock = threading.Lock()
        self._fh = open(log_path, "a", encoding="utf-8")

    def log(self, **fields):
        record = {"timestamp": time.time(), **fields}
        with self._lock:
            self._fh.write(json.dumps(record) + "\n")
            self._fh.flush()
            os.fsync(self._fh.fileno())

    def close(self):
        self._fh.close()


# --------------------------------------------------------------------------
# Checkpoint (resumable results) handling
# --------------------------------------------------------------------------

class Checkpoint:
    """Tracks per-file SUCCESSFUL results and streams them to disk as they
    arrive. Errors are never written here (see MetricsLog) - a failed file
    simply stays absent from the checkpoint and gets retried automatically
    on the next run.

    Thread-safe: process_file() runs on worker threads, all of which call
    record() when they finish successfully.
    """

    def __init__(self, checkpoint_path: str):
        self.checkpoint_path = checkpoint_path
        self._lock = threading.Lock()
        self.done: dict[str, dict] = {}  # file -> result record

        for record in read_jsonl_file(checkpoint_path):
            file_key = record.get("file")
            if file_key is None:
                continue
            self.done[file_key] = record

        # Open in append mode - existing good lines stay, new ones get added.
        # (We never rewrite the checkpoint file in place, only append.)
        self._fh = open(checkpoint_path, "a", encoding="utf-8")

    def is_done(self, file_key: str) -> bool:
        return file_key in self.done

    def record(self, result: dict):
        file_key = result["file"]
        with self._lock:
            self.done[file_key] = result
            self._fh.write(json.dumps(result) + "\n")
            self._fh.flush()
            os.fsync(self._fh.fileno())

    def all_results(self) -> list[dict]:
        with self._lock:
            return list(self.done.values())

    def close(self):
        self._fh.close()


# --------------------------------------------------------------------------
# LLM querying
# --------------------------------------------------------------------------

def build_prompt(file_content: str, entities: list[dict]) -> str:
    return PROMPT_TEMPLATE.format(
        file_content=file_content,
        entities=json.dumps(entities, indent=2),
    )


def extract_json(text: str):
    """Strip markdown fences / stray text if the model doesn't fully obey
    the 'JSON only' instruction."""
    text = text.strip()
    match = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
    if match:
        text = match.group(1).strip()
    return json.loads(text)


def is_rate_limit_error(exc: Exception) -> bool:
    msg = str(exc).lower()
    return "429" in msg or "rate_limit" in msg or "rate limit" in msg


def _extract_usage(response) -> dict:
    """Best-effort extraction of token usage from a langchain response.
    Not every backend reports this, so all fields may come back as None."""
    usage = getattr(response, "usage_metadata", None) or {}
    return {
        "input_tokens": usage.get("input_tokens"),
        "output_tokens": usage.get("output_tokens"),
        "total_tokens": usage.get("total_tokens"),
    }


def process_file(llm: ChatOpenAI, ts_path: Path, entities: list[dict],
                  max_retries: int, base_backoff: float,
                  metrics_log: MetricsLog, backend: str, model: str) -> dict | None:
    """Run one file through the LLM.

    Returns {"file": ..., "entities": [...]} on a successful, validated
    response, or None on any kind of failure (the failure itself is
    recorded in metrics_log, not returned)."""

    try:
        file_content = ts_path.read_text(encoding="utf-8")
    except OSError as e:
        metrics_log.log(file=str(ts_path), backend=backend, model=model,
                         status="error", error=f"Could not read file: {e}")
        return None

    prompt = build_prompt(file_content, entities)
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    last_error = None
    for attempt in range(max_retries + 1):
        start = time.monotonic()
        try:
            response = llm.invoke(messages)
        except Exception as e:
            latency = time.monotonic() - start
            last_error = e
            metrics_log.log(
                file=str(ts_path), backend=backend, model=model,
                attempt=attempt + 1, latency_s=round(latency, 2),
                status="error", error=f"LLM call failed: {e}",
            )
            if is_rate_limit_error(e) and attempt < max_retries:
                wait = base_backoff * (2 ** attempt)
                print(f"[RATE LIMIT] {ts_path} - waiting {wait:.0f}s (attempt {attempt + 1}/{max_retries})")
                time.sleep(wait)
                continue
            return None

        latency = time.monotonic() - start
        usage = _extract_usage(response)

        try:
            result = extract_json(response.content)
        except json.JSONDecodeError as e:
            metrics_log.log(
                file=str(ts_path), backend=backend, model=model,
                attempt=attempt + 1, latency_s=round(latency, 2), **usage,
                status="error", error=f"JSON parse failed: {e}",
                raw=response.content[:2000],
            )
            return None

        if not isinstance(result, list):
            metrics_log.log(
                file=str(ts_path), backend=backend, model=model,
                attempt=attempt + 1, latency_s=round(latency, 2), **usage,
                status="error",
                error=f"Response was not a JSON list (got {type(result).__name__})",
            )
            return None

        valid, mismatch_msg = validate_entity_keys(entities, result)
        if not valid:
            metrics_log.log(
                file=str(ts_path), backend=backend, model=model,
                attempt=attempt + 1, latency_s=round(latency, 2), **usage,
                status="error", error=f"Entity id/name mismatch: {mismatch_msg}",
            )
            return None

        metrics_log.log(
            file=str(ts_path), backend=backend, model=model,
            attempt=attempt + 1, latency_s=round(latency, 2), **usage,
            status="success", num_entities=len(result),
        )
        return {"file": str(ts_path), "entities": result}

    metrics_log.log(file=str(ts_path), backend=backend, model=model,
                     status="error", error=f"LLM call failed after retries: {last_error}")
    return None


class Pacer:
    """Very simple global pacer so concurrent workers don't collectively
    blow through RPM/TPM limits. Ensures at least `min_interval` seconds
    pass between the *start* of any two requests, across all threads."""

    def __init__(self, min_interval: float):
        self.min_interval = min_interval
        self._lock = threading.Lock()
        self._last_call = 0.0

    def wait_turn(self):
        with self._lock:
            now = time.monotonic()
            wait = self._last_call + self.min_interval - now
            if wait > 0:
                time.sleep(wait)
            self._last_call = time.monotonic()


def process_repo(llm: ChatOpenAI, file_entity_map: dict[Path, list[dict]],
                  checkpoint: Checkpoint, metrics_log: MetricsLog,
                  backend: str, model: str, max_workers: int,
                  min_interval: float, max_retries: int, base_backoff: float):
    pacer = Pacer(min_interval)

    to_process = {
        path: entities for path, entities in file_entity_map.items()
        if not checkpoint.is_done(str(path))
    }
    skipped_count = len(file_entity_map) - len(to_process)
    if skipped_count:
        print(f"[INFO] Skipping {skipped_count} file(s) already in checkpoint")
    print(f"[INFO] Processing {len(to_process)} file(s)")

    if not to_process:
        return

    from concurrent.futures import ThreadPoolExecutor, as_completed

    def worker(path, entities):
        pacer.wait_turn()
        result = process_file(llm, path, entities, max_retries, base_backoff,
                               metrics_log, backend, model)
        if result is not None:
            checkpoint.record(result)
        return result

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(worker, path, entities): path
            for path, entities in to_process.items()
        }
        completed = 0
        for future in as_completed(futures):
            path = futures[future]
            completed += 1
            try:
                result = future.result()
                if result is None:
                    print(f"[FAILED {completed}/{len(to_process)}] {path}: see metrics log")
                else:
                    print(f"[OK {completed}/{len(to_process)}] {path} ({len(result['entities'])} entities)")
            except Exception as e:
                print(f"[FAILED {completed}/{len(to_process)}] {path}: {e}")
                metrics_log.log(file=str(path), backend=backend, model=model,
                                 status="error", error=f"Unhandled exception: {e}")


# --------------------------------------------------------------------------
# Merge descriptions back into the full dataset
# --------------------------------------------------------------------------

def merge_descriptions(data: list[dict], results: list[dict]) -> list[dict]:
    """Merge descriptions from checkpointed results into the full entity
    list. Since the checkpoint only ever contains validated results
    (entities is guaranteed to be a list of dicts whose keys exactly match
    the input for that file), this needs no defensive checks."""

    desc_lookup: dict[tuple, str] = {}
    for r in results:
        for ent in r.get("entities", []):
            desc_lookup[(r["file"], entity_key(ent))] = ent.get("description")

    updated = []
    for entity in data:
        entity = dict(entity)
        key_name = entity_key(entity)
        entity_file = entity.get("file")

        for (file_key, name_key), desc in desc_lookup.items():
            if name_key != key_name:
                continue
            file_key_norm = file_key.replace("\\", "/")
            file_match = isinstance(entity_file, str) and file_key_norm.endswith(entity_file.replace("\\", "/"))
            if file_match:
                entity["description"] = desc
                break
        updated.append(entity)
    return updated


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    _llm_config = load_llm_config()
    parser.add_argument("--tag", required=True,
                        help="Folder tag, e.g. <owner>_<repo>_<branch>. "
                             "Reads from data/raw/<tag>/ and data/processed/<tag>/, "
                             "writes to data/processed/<tag>/")
    parser.add_argument("--llm", choices=sorted(_llm_config.keys()),
                        default=os.environ.get("LLM_BACKEND", "local"),
                        help=f"Which LLM backend to use (default: local, or $LLM_BACKEND if set). "
                             f"Available: {', '.join(sorted(_llm_config.keys()))}")
    parser.add_argument("--max-tokens", type=int, default=2048)
    parser.add_argument("--num-files", type=int, default=None, help="Only process the first N files (default: all)")
    parser.add_argument("--max-workers", type=int, default=2, help="Concurrent LLM requests")
    parser.add_argument("--min-interval", type=float, default=2.5,
                        help="Minimum seconds between the start of any two requests (global pacer, across all workers)")
    parser.add_argument("--max-retries", type=int, default=1, help="Retries on rate-limit (429) errors before giving up on a file")
    parser.add_argument("--base-backoff", type=float, default=5.0, help="Base seconds for exponential backoff on rate limits")
    args = parser.parse_args()

    processed_dir = os.path.join("data", "processed", args.tag)
    root_folder = os.path.join("data", "raw", args.tag)
    input_path = os.path.join(processed_dir, "entities.jsonl")
    output_path = os.path.join(processed_dir, "entities_with_desc.jsonl")
    log_folderpath = os.path.join(processed_dir, "add-descriptions-intermediate")

    checkpoint_path = os.path.join(log_folderpath, "entities_raw_results.jsonl")
    metrics_log_path = os.path.join(log_folderpath, "llm_call_metrics.jsonl")

    if not os.path.isdir(root_folder):
        parser.error(f"Root folder not found: {root_folder}")
    if not os.path.isfile(input_path):
        parser.error(f"Input entities file not found: {input_path}")

    os.makedirs(processed_dir, exist_ok=True)
    os.makedirs(log_folderpath, exist_ok=True)

    model_name = _llm_config[args.llm]["model"]

    llm = build_llm(
        backend=args.llm,
        max_tokens=args.max_tokens,
        config = _llm_config
    )
    print(f"[INFO] Using {args.llm} backend ({model_name})")

    data = read_jsonl_file(input_path)
    file_entity_map = build_file_entity_map(data, root_folder)

    if args.num_files is not None:
        file_entity_map = dict(islice(file_entity_map.items(), args.num_files))

    checkpoint = Checkpoint(checkpoint_path)
    metrics_log = MetricsLog(metrics_log_path)
    metrics_log.log(event="run_start", backend=args.llm, model=model_name,
                     num_files=len(file_entity_map), max_workers=args.max_workers)

    try:
        process_repo(
            llm, file_entity_map, checkpoint, metrics_log,
            backend=args.llm, model=model_name,
            max_workers=args.max_workers,
            min_interval=args.min_interval,
            max_retries=args.max_retries,
            base_backoff=args.base_backoff,
        )
    finally:
        checkpoint.close()

    results = checkpoint.all_results()
    print(f"[INFO] Checkpoint has {len(results)} successful result(s) "
          f"(check {metrics_log_path} for any failures)")

    merged = merge_descriptions(data, results)

    with open(output_path, "w", encoding="utf-8") as f:
        for entry in merged:
            f.write(json.dumps(entry) + "\n")

    total = len(merged)
    missing = sum(1 for e in merged if not e.get("description"))
    missing_pct = (missing / total * 100) if total else 0.0
    print(f"[INFO] Wrote {total} entities to {output_path}")
    print(f"[INFO] {missing}/{total} entities ({missing_pct:.1f}%) have no description")

    metrics_log.log(event="run_end", total_entities=total,
                     entities_missing_description=missing,
                     missing_description_pct=round(missing_pct, 2))
    metrics_log.close()


if __name__ == "__main__":
    main()